Repository Sakuten/frontend, pull requests merged in 2018-07, with the labels that each got.

#15 Netlify Support
  netlify.toml
Labels: enhancement

#23 Fix: Make netlify deployment work correctly
  netlify.toml
Labels: Immediate

#27 Add: Auto install dependencies
  Dockerfile.dev
  package.json
  yarn.lock
Labels: Immediate

#31 Change: Use API_SERVER from cookie in development build
  package.json
  src/api/request.js
  yarn.lock
Labels: enhancement

#37 Add: Add routing
  package.json
  src/component/Home.js
  src/component/__tests__/Home.spec.js
  src/component/__tests__/__snapshots__/Home.spec.js.snap
  src/container/App.js
  src/container/__tests__/App.spec.js
  src/container/__tests__/__snapshots__/App.spec.js.snap
  src/container/__tests__/__snapshots__/ApplicationView.spec.js.snap
  src/container/__tests__/__snapshots__/LoginView.spec.js.snap
  src/index.js
  src/store/index.js
  yarn.lock
Labels: Immediate, enhancement, investigation required

#52 recaptcha対応
  package.json
  public/index.html
  src/api/operation/authenicate.js
  src/container/LoginView.js
  src/container/__tests__/LoginView.spec.js
  src/container/__tests__/__snapshots__/App.spec.js.snap
  src/container/__tests__/__snapshots__/ApplicationView.spec.js.snap
  src/container/__tests__/__snapshots__/LoginView.spec.js.snap
  src/event/__tests__/credential.spec.js
  src/event/credential.js
  src/store/__tests__/credential.spec.js
  src/store/credential.js
  yarn.lock
Labels: enhancement

#56 Delete: Delete <script> loading recaptcha
  public/index.html
Labels: Immediate, bug, difficult to reproduce

#57 Fix Uncaught TypeError in recaptchaResponse - #53
  src/container/LoginView.js
  src/event/credential.js
Labels: bug

#50 Fix: Fix to redirect when login/logout
  src/event/__tests__/credential.spec.js
  src/event/credential.js
Labels: Immediate, bug

#49 Fix: Enable `API_SERVER` injection in netlify build
  netlify.toml
  src/api/request.js
Labels: Immediate, bug, partial

#54 Change: Use ID Authentication and Add QR Reader
  netlify.toml
  package.json
  src/api/operation/__mocks__/authenicate.js
  src/api/operation/__mocks__/getStatus.js
  src/api/operation/authenicate.js
  src/component/QRReader.js
  src/container/ApplicationView.js
  src/container/LoginView.js
  src/container/__tests__/LoginView.spec.js
  src/container/__tests__/__snapshots__/App.spec.js.snap
  src/container/__tests__/__snapshots__/ApplicationView.spec.js.snap
  src/container/__tests__/__snapshots__/LoginView.spec.js.snap
  src/event/__tests__/credential.spec.js
  src/event/credential.js
  src/store/__tests__/credential.spec.js
  src/store/credential.js
  yarn.lock
Labels: enhancement
