Repository Sakuten/frontend, pull requests merged in 2018-09, with the labels that each got.

#72 PULL_REQUEST_TEMPLATE.md書き換え
  .github/PULL_REQUEST_TEMPLATE.md
Labels: small

#73 Use recaptcha 3
  package.json
  src/container/App.js
  src/container/LoginView.js
  src/container/__tests__/LoginView.spec.js
  yarn.lock
Labels: enhancement

#75 UI refinements
  package.json
  src/component/Button.js
  src/component/Home.js
  src/component/__tests__/Button.spec.js
  src/component/__tests__/__snapshots__/Button.spec.js.snap
  src/component/__tests__/__snapshots__/Home.spec.js.snap
  src/container/App.js
  src/container/ApplicationView.js
  src/header.svg
  src/sakuten.jpg
  yarn.lock
Labels: enhancement

#78 Show only available lottery
  src/api/operation/__mocks__/getLotteries.js
  src/api/operation/getLotteries.js
  src/component/LotterySelect.js
  src/component/LotteryView.js
  src/component/__tests__/LotterySelect.spec.js
  src/component/__tests__/LotteryView.spec.js
  src/component/__tests__/__snapshots__/LotterySelect.spec.js.snap
  src/component/__tests__/__snapshots__/LotteryView.spec.js.snap
  src/container/ApplicationView.js
  src/container/__tests__/ApplicationView.spec.js
Labels: enhancement

#91 団体応募を4人までにする #80
  src/component/GroupMemberButton.js
  src/component/__tests__/__snapshots__/GroupMemberButton.spec.js.snap
  src/container/ApplicationView.js
  src/event/__tests__/application.spec.js
  src/event/application.js
  src/store/application.js
Labels: enhancement

#92 第index+1公演→第index+2公演
  src/component/LotteryView.js
  src/component/__tests__/LotteryView.spec.js
  src/component/__tests__/__snapshots__/LotteryView.spec.js.snap
Labels: bug

#93 有人受付UI
  src/component/Home.js
  src/component/__tests__/__snapshots__/Home.spec.js.snap
  src/container/App.js
  src/container/ApplicationView.js
  src/container/__tests__/ApplicationView.spec.js
  src/container/__tests__/__snapshots__/App.spec.js.snap
  src/container/__tests__/__snapshots__/ApplicationView.spec.js.snap
  src/container/__tests__/__snapshots__/LoginView.spec.js.snap
  src/event/__tests__/application.spec.js
  src/event/application.js
  src/event/credential.js
  src/store/__tests__/credential.spec.js
  src/store/credential.js
Labels: enhancement

#94 メンバーリストにpublic IDを表示する
  src/api/operation/__mocks__/getPublicId.js
  src/api/operation/__mocks__/index.js
  src/api/operation/getPublicId.js
  src/api/operation/index.js
  src/component/GroupMemberList.js
  src/component/__tests__/GroupMemberList.spec.js
  src/component/__tests__/__snapshots__/GroupMemberList.spec.js.snap
  src/container/ApplicationView.js
  src/event/__tests__/application.spec.js
  src/event/application.js
  src/store/__tests__/application.spec.js
  src/store/application.js
Labels: enhancement

#97 メンバーリストのUI
  src/component/GroupMemberList.js
  src/component/__tests__/__snapshots__/GroupMemberList.spec.js.snap
Labels: enhancement

#103 Fulfilledなapplicationにcancelをつけない
  src/component/ApplicationList.js
  src/component/__tests__/ApplicationList.spec.js
Labels: 0907-trial, enhancement, small

#104 Show 'OK' Button on error message
  src/component/ErrorList.js
  src/component/__tests__/ErrorList.spec.js
  src/component/__tests__/__snapshots__/ErrorList.spec.js.snap
Labels: enhancement

#106 応募、キャンセル時にメッサージボックスを
  src/component/MessageDialog.js
  src/component/__tests__/MessageDialog.spec.js
  src/component/__tests__/__snapshots__/MessageDialog.spec.js.snap
  src/container/App.js
  src/container/ApplicationView.js
  src/container/__tests__/__snapshots__/App.spec.js.snap
  src/container/__tests__/__snapshots__/ApplicationView.spec.js.snap
  src/container/__tests__/__snapshots__/CheckerView.spec.js.snap
  src/container/__tests__/__snapshots__/LoginView.spec.js.snap
  src/event/__tests__/application.spec.js
  src/event/__tests__/dialog.spec.js
  src/event/__tests__/index.spec.js
  src/event/application.js
  src/event/dialog.js
  src/event/index.js
  src/store/__tests__/dialog.spec.js
  src/store/dialog.js
  src/store/index.js
Labels: enhancement

#108 Fix: Use api.sakuten.jp on master branch, use heroku otherwise
  netlify.toml
Labels: Immediate, enhancement

#114 ログインに失敗したらQR読み取りに戻す
  src/event/credential.js
  src/event/error.js
Labels: enhancement

#111 日付変更によるUser無効化時に別のエラーを表示
  src/errors.json
Labels: enhancement

#115 Change: Store last classroom id on localstorage
  src/store/checker.js
Labels: enhancement

#122 応募の情報を詳細に表示
  src/api/operation/__mocks__/applyLottery.js
  src/api/operation/__mocks__/getApplications.js
  src/component/ApplicationList.js
  src/component/__tests__/ApplicationList.spec.js
  src/component/__tests__/__snapshots__/ApplicationList.spec.js.snap
  src/event/index.js
Labels: enhancement

#123 応募のユーザー入力をログイン・応募時にクリア
  src/event/credential.js
  src/event/index.js
  src/store/__tests__/application.spec.js
  src/store/application.js
Labels: bug

#127 Change: Use kind words in Unauthorized
  src/component/__tests__/__snapshots__/ErrorList.spec.js.snap
  src/errors.json
Labels: enhancement, small

#126 発表時間にstatus再取得
  package.json
  src/index.js
  src/util/checkAndFetch.js
  yarn.lock
Labels: enhancement

#129 劇の名前を表示
  src/api/operation/__mocks__/getClassrooms.js
  src/component/ClassroomSelect.js
  src/component/__tests__/ClassroomSelect.spec.js
  src/component/__tests__/__snapshots__/ClassroomSelect.spec.js.snap
Labels: enhancement

#135 団体応募メンバー追加ボタンをわかりやすく
  src/container/ApplicationView.js
Labels: enhancement

#136 Sakuten/backend#230対応 自分がメンバーかを表示
  src/api/operation/__mocks__/getApplications.js
  src/component/ApplicationList.js
  src/component/__tests__/ApplicationList.spec.js
  src/component/__tests__/__snapshots__/ApplicationList.spec.js.snap
Labels: enhancement
